apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: msrrepo1.azurecr.io/poc/sampleapp:0.2
        ports:
        - containerPort: 5042
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-svc
spec:
  type: LoadBalancer
  ports:
    - name: "responder"
      port: 80
      targetPort: 5042
  selector:
    app: myapp
